# Generated by Django 3.2.9 on 2022-03-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ogr2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyad', models.CharField(max_length=50)),
                ('aciklama', models.TextField(max_length=250)),
            ],
        ),
    ]
