# Generated by Django 3.2.9 on 2022-03-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_ogr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogr2',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='kisiresmi/', verbose_name='kisi Resmi Ekleyin'),
        ),
    ]
