# Generated by Django 3.2.9 on 2022-04-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_ogr2_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogr2',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anasayfa.ogr'),
        ),
    ]
